version: '3'

services:
  shiftlist-parser:
    build: .
    stdin_open: true
    tty: true
    command: sh -c "gunicorn -w 2 -b :8556 'webparser:app'"
    container_name: shiftlist-parser
    volumes:
      - .:/webparser
    ports:
      - "8556:8556"